window.ARCANIST_EXAMPLES = {
  "Demo 1": {
    "id": "ceve9lhyn",
    "type": "empty",
    "name": "Group Folder 1",
    "parentId": null,
    "x": 0,
    "y": 8,
    "radius": 0,
    "symmetry": 0,
    "edgeIndex": -1,
    "independentEdges": false,
    "visible": true,
    "rotation": 0,
    "rotationSpeed": 0,
    "drawOuterCircle": true,
    "outerThickness": 1.5,
    "outerDashed": false,
    "outerDashConfig": "10, 5",
    "doubleRim": false,
    "rimGap": 8,
    "drawPerimeter": true,
    "connectPoints": false,
    "connectPointsSkip": 1,
    "connectMidPoints": false,
    "symbolsAtPoints": false,
    "symbolText": "\u263f\u2640\u2641\u2642\u2643\u2644",
    "centerSymbol": false,
    "centerSymbolText": "\ud83d\udf14",
    "linesCenter": false,
    "inscribe": false,
    "textContent": "ARCANE",
    "fontSize": 24,
    "fontWeight": 400,
    "letterSpacing": 5,
    "straightText": false,
    "color": "#ffffff",
    "children": [
      {
        "id": "y68e8yvxf",
        "type": "magic",
        "name": "Magic Circle 1",
        "parentId": "ceve9lhyn",
        "x": 0,
        "y": 8,
        "radius": 180,
        "symmetry": 6,
        "edgeIndex": -1,
        "independentEdges": false,
        "visible": true,
        "rotation": 0,
        "rotationSpeed": 0,
        "drawOuterCircle": true,
        "outerThickness": 1.5,
        "outerDashed": false,
        "outerDashConfig": "10, 5",
        "doubleRim": false,
        "rimGap": 8,
        "drawPerimeter": true,
        "connectPoints": true,
        "connectPointsSkip": 2,
        "connectMidPoints": false,
        "symbolsAtPoints": false,
        "symbolText": "\u263f\u2640\u2641\u2642\u2643\u2644",
        "centerSymbol": false,
        "centerSymbolText": "\ud83d\udf14",
        "linesCenter": false,
        "inscribe": false,
        "textContent": "ARCANE",
        "fontSize": 24,
        "fontWeight": 400,
        "letterSpacing": 5,
        "straightText": false,
        "color": "#ffffff",
        "children": [
          {
            "id": "wg1ouu2wl",
            "type": "shape",
            "name": "True Polygon 1",
            "parentId": "y68e8yvxf",
            "x": 0,
            "y": 0,
            "radius": 54,
            "symmetry": 6,
            "edgeIndex": -1,
            "independentEdges": false,
            "visible": true,
            "rotation": 0,
            "rotationSpeed": 0,
            "drawOuterCircle": false,
            "outerThickness": 1.5,
            "outerDashed": false,
            "outerDashConfig": "10, 5",
            "doubleRim": false,
            "rimGap": 8,
            "drawPerimeter": true,
            "connectPoints": true,
            "connectPointsSkip": 2,
            "connectMidPoints": true,
            "symbolsAtPoints": false,
            "symbolText": "\u263f\u2640\u2641\u2642\u2643\u2644",
            "centerSymbol": false,
            "centerSymbolText": "\ud83d\udf14",
            "linesCenter": false,
            "inscribe": false,
            "textContent": "ARCANE",
            "fontSize": 24,
            "fontWeight": 400,
            "letterSpacing": 5,
            "straightText": false,
            "color": "#ffffff",
            "children": []
          }
        ]
      }
    ]
  }
};